### ISSUE TITLE
Missing path to repo

### ISSUE THREAD

**Issue by fullofcaffeine** [luispabon/borg-s3-home-backup#1]
Hey Luis,

Good stuff you've got here. Borg is pretty good and I think I finally found my final cross-platform backup solution, and your S3 script is the icing on the cake.

I did go through an issue though, it looks like the path to the repo is missing here: https://github.com/luispabon/borg-s3-home-backup/blob/master/borg-backup.sh#L31. I added `${BACKUP_REPO}` before `::{BACKUP_NAME}` and it worked, otherwise `borg` fails with:

```
borg create: error: argument ARCHIVE: Invalid location format: "::home"
``` 

I'll gladly create a PR to fix this, but at the moment I'm not at my main computer, and just wanted to make sure you're aware of it.

**Comment by luispabon** [comment]
Hey! It totally should work with BORG_REPO in your environment, looks to me like you might have a significantly different version of borg where that is a syntax error. I'm currently at 1.0.11 (1.1.2 seems to be their latest stable release), which is packaged with Ubuntu 17.10; what version you do have? 

This is happening on cron, or when you run it manually? Do you get anything when you execute `borg list`?
