### ISSUE TITLE
Different approach...

### ISSUE THREAD

**Issue by oderwat** [luispabon/borg-s3-home-backup#2]
Not much to say but:

1. try rclone instead awscli. It makes your script using much more possible backends.
2. use wasabi.com instead of amazon s3. It is much cheaper and also faster.

**Comment by luispabon** [comment]
Thank you for the suggestion. I'm keeping this narrow on purpose, for other use cases there's different tooling, some of which natively supported by borg itself.

**Comment by fullofcaffeine** [comment]
@oderwat Interesting, I'm satisfied with s3 at the moment but I might look into `wasabi`. I assume `rclone` supports it? If so, it'd be a matter of replacing the `awscli` call with a rclone call to sync to wasabi, no?
