### ISSUE TITLE
use `borg with-lock` when syncing

### ISSUE THREAD

**Issue by Ciantic** [luispabon/borg-s3-home-backup#3]
I just noticed that it's [recommended](https://github.com/borgbackup/borg/issues/989) to use `borg with-lock` ([docs](https://borgbackup.readthedocs.io/en/stable/usage/lock.html)) when syncing, because if the aws s3 sync script happens to run when another borg command is going on it will mess up the sync.

**Comment by luispabon** [comment]
Thank you for the heads up, I had no idea this was an option. @Ciantic could you please have a quick look at https://github.com/luispabon/borg-s3-home-backup/pull/4 ? Works for me on my setup but would be good to have an extra pair of eyes.

Tested as follows:
  * Run the backup
  * While it runs, on another terminal run `watch -n1 borg list`, which should output `Failed to create/acquire the lock /storage/borg-backup/lock.exclusive (timeout).` until backup finishes

**Comment by Ciantic** [comment]
I've never used borg to be honest. Looks right to me, haven't tested.

**Comment by luispabon** [comment]
lol copy that. So if you don't use borg, how come you're here?

**Comment by Ciantic** [comment]
Since you asked, I'm here because I like this script! 

I'm about to transition using to borg when I have time to set all things up. Currently using backblaze, but using it is not same as owning your backups.
